package bib;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/** Classe de interface gráfica que mostra uma janela com os dados do Artigo.
 * <p> Mostra os dados do artigo. Se o utilizador ligado ao sistema for um administrador
 * permite aumentar ou diminuir o número de cópias do Artigo, bem como ver todas
 * as requisiçoes associadas. Se for um Leitor permite requisitar o artigo.
 * @author André Baptista (2012137523)
 * @author Rosa Faria (2005128014)
 */
public class DisplayArtigo extends javax.swing.JFrame {
	private Artigo artigo;
	private Utilizador requester;
	private ArrayList<ArrayList> dados;
	
	/** Cria uma nova janela DisplayArtigo.
	 * Retira as opções que não estiverem disponíveis ao tipo de Utilizador que fez login
	 * @param artigo Artigo a mostrar
	 * @param requester Utilizador ligado ao sistema
	 * @param dados Dados do sistema
	 */
	public DisplayArtigo(Artigo artigo, Utilizador requester, ArrayList<ArrayList> dados) {
		this.setContentPane(new JLabel(new ImageIcon(getClass().getResource("/bib/resources/bckgrnd.png"))));
		this.setIconImage(new ImageIcon(getClass().getResource("/bib/resources/Logo.gif")).getImage());
		initComponents();
		this.setLocationRelativeTo(null);
		
		/**Inicializar atributos**/
		this.artigo = artigo;
		this.requester = requester;
		this.dados = dados;
		
		/**Definir visibilidade de opções consoante permissões**/
		if (requester instanceof Leitor) {
			this.add.setVisible(false);
			this.delete.setVisible(false);
			this.requisicoes.setText("Requisitar");
			if (this.artigo.availCopy()<=0) this.requisicoes.setVisible(false);
		}
		
		/**Definir campos a utilizar consoante o tipo de artigo**/
		if (artigo instanceof DVD) {
			this.autoresLabel.setText("Realizador");
			this.autores.setText(((DVD)artigo).getRealizador());
			this.cotaLabel.setText("Duração");
			this.cota.setText(""+((DVD)artigo).getDuracao());
			this.isbnLabel.setText("");
			this.isbn.setVisible(false);
		}
		else {
			String autoresString = ""+((Livro)artigo).getAutores().get(0).getNome();
			for (int i = 1; i<((Livro)artigo).getAutores().size();i++)
				autoresString+="; "+((Livro)artigo).getAutores().get(i).getNome();
			this.autores.setText(autoresString);
			this.cota.setText(((Livro)artigo).getCota());
			this.isbn.setText(((Livro)artigo).getIsbn());
		}
		this.titulo.setText(artigo.getTitulo());
		this.editora.setText(artigo.getEditora());
		this.ano.setText(""+artigo.getAnoPublicacao());
		this.ncopias.setText(""+artigo.getnCopias());
		this.nreqs.setText(""+artigo.getnRequisitados());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JTextField();
        editora = new javax.swing.JTextField();
        autores = new javax.swing.JTextField();
        ano = new javax.swing.JTextField();
        ncopias = new javax.swing.JTextField();
        nreqs = new javax.swing.JTextField();
        cota = new javax.swing.JTextField();
        isbn = new javax.swing.JTextField();
        tituloLabel = new javax.swing.JLabel();
        editoraLabel = new javax.swing.JLabel();
        autoresLabel = new javax.swing.JLabel();
        anoLabel = new javax.swing.JLabel();
        cotaLabel = new javax.swing.JLabel();
        isbnLabel = new javax.swing.JLabel();
        copiasLabel = new javax.swing.JLabel();
        reqsLabel = new javax.swing.JLabel();
        requisicoes = new javax.swing.JButton();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setResizable(false);

        titulo.setEditable(false);

        editora.setEditable(false);

        autores.setEditable(false);

        ano.setEditable(false);

        ncopias.setEditable(false);

        nreqs.setEditable(false);

        cota.setEditable(false);

        isbn.setEditable(false);

        tituloLabel.setText("Título:");

        editoraLabel.setText("Editora:");

        autoresLabel.setText("Autores:");

        anoLabel.setText("Ano de publicação:");

        cotaLabel.setText("Cota:");

        isbnLabel.setText("ISBN:");

        copiasLabel.setText("Número de cópias existentes:");

        reqsLabel.setText("Número de cópias requisitadas:");

        requisicoes.setText("Ver requisições");
        requisicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requisicoesActionPerformed(evt);
            }
        });

        add.setText("+");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delete.setText("-");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(reqsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nreqs, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(requisicoes)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(copiasLabel)
                        .addGap(27, 27, 27)
                        .addComponent(ncopias, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloLabel)
                            .addComponent(editoraLabel)
                            .addComponent(autoresLabel)
                            .addComponent(isbnLabel)
                            .addComponent(cotaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ano)
                            .addComponent(isbn)
                            .addComponent(editora, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(autores)
                            .addComponent(cota, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editoraLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(autoresLabel))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cotaLabel)
                    .addComponent(cota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnLabel)
                    .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ncopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add)
                    .addComponent(delete)
                    .addComponent(copiasLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reqsLabel)
                    .addComponent(nreqs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requisicoes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
		this.artigo.setnCopias(this.artigo.getnCopias()+1); /**Adicionar cópia de artigo**/
		this.ncopias.setText(""+artigo.getnCopias());
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
 		((Admin)this.requester).removeCopy(this.artigo); /**eliminar cópia de artigo**/
		this.ncopias.setText(""+artigo.getnCopias());
    }//GEN-LAST:event_deleteActionPerformed

    private void requisicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requisicoesActionPerformed
		/**Se o utilizador ligado é um Administrador pode consultar todas as requisições do artigo
		 * Senão, é um Leitor, e pode requisitar o artigo.
		 */
		if (this.requester instanceof Admin) { /**Ver todas as requisições**/
			ArrayList<Requisicao> temp= new ArrayList<>();
			for (int i = 0; i<dados.get(3).size();i++)
				if (((Requisicao)dados.get(3).get(i)).getArtigo()==(this.artigo))
					temp.add((Requisicao)dados.get(3).get(i));
			PickFromList j = new PickFromList(temp.toArray(), requester, dados);
			j.setVisible(true);
			Search.frames.add(j);
		}
		else {/**Criar nova requisição**/
			if (((Leitor)this.requester).requisitar(this.artigo, this.dados.get(3))==1) {
				JOptionPane.showMessageDialog(null, "Requisitou este artigo", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
				if (this.artigo.availCopy()<=0) this.requisicoes.setVisible(false);
				this.nreqs.setText(""+Integer.parseInt(this.nreqs.getText()+1));
			}
			else
				JOptionPane.showMessageDialog(null, "Não pode fazer mais requisições", "Erro", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_requisicoesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField ano;
    private javax.swing.JLabel anoLabel;
    private javax.swing.JTextField autores;
    private javax.swing.JLabel autoresLabel;
    private javax.swing.JLabel copiasLabel;
    private javax.swing.JTextField cota;
    private javax.swing.JLabel cotaLabel;
    private javax.swing.JButton delete;
    private javax.swing.JTextField editora;
    private javax.swing.JLabel editoraLabel;
    private javax.swing.JTextField isbn;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JTextField ncopias;
    private javax.swing.JTextField nreqs;
    private javax.swing.JLabel reqsLabel;
    private javax.swing.JButton requisicoes;
    private javax.swing.JTextField titulo;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
