package bib;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 * Classe de interface gráfica que mostra uma janela com os dados da Requisicao.
 * <p>
 * Mostra os dados da Requisição: Leitor, Artigo, data de início, data de fim e data de entrega. 
 * Permite ver os detalhes do Leitor e do Artigo. Se o utilizador que fez login 
 * é o mesmo da reserva pode entregar o Artigo em questão.
 * @author André Baptista (2012137523)
 * @author Rosa Faria (2005128014)
 */
public class DisplayReq extends javax.swing.JFrame {
	private Requisicao req;
	private Utilizador user;
	private ArrayList<ArrayList> dados;
	/**
	 * Cria uma nova janela DisplayReq.
	 * Desactiva o botão "Entregar" se o utilizador que fez Login não for o que fez a Requisição
	 * @param req Requisição a mostrar
	 * @param user Utilizador ligado ao sistema
	 * @param dados Dados do sistema
	 */
	public DisplayReq(Requisicao req, Utilizador user, ArrayList<ArrayList> dados) {
		this.setContentPane(new JLabel(new ImageIcon(getClass().getResource("/bib/resources/bckgrnd.png"))));
		this.setIconImage(new ImageIcon(getClass().getResource("/bib/resources/Logo.gif")).getImage());
		initComponents();
		this.setLocationRelativeTo(null);
		
		/**Inicializar atributos**/
		this.req = req;
		this.user = user;
		this.dados = dados;
		if (this.user != req.getLeitor())//só o próprio utilizador é que pode entregar
			this.entregar.setVisible(false);
		
		/**Carregar dados para os respectivos campos**/
		this.artigo.setText(req.getArtigo().getTitulo());
		if (this.req.getLeitor()==null) {
			this.utilizador.setText("Utilizador não encontrado");
			this.userPlus.setVisible(false);
		}
		else this.utilizador.setText(""+req.getLeitor().getnInterno()+": "+req.getLeitor().getNome());
		
		this.ano.setText(""+req.getDataInicio().getAno());
		this.mes.setText(""+req.getDataInicio().getMes());
		this.dia.setText(""+req.getDataInicio().getDia());
		this.ano1.setText(""+req.getDataFim().getAno());
		this.mes1.setText(""+req.getDataFim().getMes());
		this.dia1.setText(""+req.getDataFim().getDia());
		
		try { //pode ainda não ter sido entregue - data de entrega é null
			this.ano2.setText(""+req.getDataEntrega().getAno());
			this.mes2.setText(""+req.getDataEntrega().getMes());
			this.dia2.setText(""+req.getDataEntrega().getDia());
			if (this.user instanceof Leitor) this.entregar.setVisible(false);
		}
		catch (NullPointerException e) {}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userPlus = new javax.swing.JButton();
        artigoPlus = new javax.swing.JButton();
        utilizador = new javax.swing.JTextField();
        artigo = new javax.swing.JTextField();
        entregar = new javax.swing.JButton();
        slash2 = new javax.swing.JLabel();
        slash1 = new javax.swing.JLabel();
        dia = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        ano = new javax.swing.JTextField();
        slash3 = new javax.swing.JLabel();
        slash4 = new javax.swing.JLabel();
        dia1 = new javax.swing.JTextField();
        mes1 = new javax.swing.JTextField();
        ano1 = new javax.swing.JTextField();
        slash5 = new javax.swing.JLabel();
        slash6 = new javax.swing.JLabel();
        dia2 = new javax.swing.JTextField();
        mes2 = new javax.swing.JTextField();
        ano2 = new javax.swing.JTextField();

        setResizable(false);

        jLabel1.setText("Leitor:");

        jLabel2.setText("Artigo:");

        jLabel3.setText("Data de requisição:");

        jLabel4.setText("Data limite:");

        jLabel5.setText("Data de entrega:");

        userPlus.setText("Ver mais");
        userPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPlusActionPerformed(evt);
            }
        });

        artigoPlus.setText("Ver mais");
        artigoPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artigoPlusActionPerformed(evt);
            }
        });

        utilizador.setEditable(false);
        utilizador.setText(" ");

        artigo.setEditable(false);
        artigo.setText(" ");

        entregar.setText("Entregar");
        entregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregarActionPerformed(evt);
            }
        });

        slash2.setText("/");

        slash1.setText("/");

        dia.setEditable(false);

        mes.setEditable(false);

        ano.setEditable(false);

        slash3.setText("/");

        slash4.setText("/");

        dia1.setEditable(false);

        mes1.setEditable(false);

        ano1.setEditable(false);

        slash5.setText("/");

        slash6.setText("/");

        dia2.setEditable(false);

        mes2.setEditable(false);

        ano2.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(utilizador)
                            .addComponent(artigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userPlus, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(artigoPlus, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dia1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(slash3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mes1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(slash4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ano1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(slash2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(slash1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dia2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(entregar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(slash5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mes2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(slash6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ano2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 106, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userPlus)
                    .addComponent(utilizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(artigoPlus)
                    .addComponent(artigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(slash1)
                        .addComponent(slash2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ano1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(slash4)
                        .addComponent(slash3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ano2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(slash6)
                        .addComponent(slash5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(entregar)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPlusActionPerformed
  		/**Ver dados do utilizador**/
		Display novo = new Display(this.req.getLeitor(), this.user, dados); 
		novo.setVisible(true);
		Search.frames.add(novo);
    }//GEN-LAST:event_userPlusActionPerformed

    private void artigoPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artigoPlusActionPerformed
		/**Ver dados do artigo**/
		DisplayArtigo novo = new DisplayArtigo(this.req.getArtigo(), this.user, dados);
		novo.setVisible(true);
		Search.frames.add(novo);
    }//GEN-LAST:event_artigoPlusActionPerformed

    private void entregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregarActionPerformed
        /*ªEntregar**/
		this.req.getLeitor().entregar(this.req.getArtigo());
		
		/**Actualizar data de entrega**/
		this.ano2.setText(""+req.getDataEntrega().getAno());
		this.mes2.setText(""+req.getDataEntrega().getMes());
		this.dia2.setText(""+req.getDataEntrega().getDia());
		
		/**Desctivar botão de entregar**/
		if (this.user instanceof Leitor) this.entregar.setVisible(false);
    }//GEN-LAST:event_entregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ano;
    private javax.swing.JTextField ano1;
    private javax.swing.JTextField ano2;
    private javax.swing.JTextField artigo;
    private javax.swing.JButton artigoPlus;
    private javax.swing.JTextField dia;
    private javax.swing.JTextField dia1;
    private javax.swing.JTextField dia2;
    private javax.swing.JButton entregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField mes;
    private javax.swing.JTextField mes1;
    private javax.swing.JTextField mes2;
    private javax.swing.JLabel slash1;
    private javax.swing.JLabel slash2;
    private javax.swing.JLabel slash3;
    private javax.swing.JLabel slash4;
    private javax.swing.JLabel slash5;
    private javax.swing.JLabel slash6;
    private javax.swing.JButton userPlus;
    private javax.swing.JTextField utilizador;
    // End of variables declaration//GEN-END:variables
}
