package bib;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/** Classe de interface gráfica para mostrar os dados de um utilizador.
 * Permite editar os dados do utilizador,  bem como remover ou ver requisições do mesmo
 * @author André Baptista (2012137523)
 * @author Rosa Faria (2005128014)
 */
public class Display extends javax.swing.JFrame {

	private Utilizador user, requester;
	private ArrayList<ArrayList> dados;
	
	/** Cria uma nova janela Display.
	 * <p> Se o utilizador não for Administrador não tem botão para remover utilizador
	 * @param user Utilizador cujos dados se quer ver
	 * @param requester Utilizador ligado ao sistema
	 * @param dados Dados do sistema
	 */
	public Display(Utilizador user, Utilizador requester, ArrayList<ArrayList> dados) {
		this.setContentPane(new JLabel(new ImageIcon(getClass().getResource("/bib/resources/bckgrnd.png"))));
		this.setIconImage(new ImageIcon(getClass().getResource("/bib/resources/Logo.gif")).getImage());
		initComponents();
		this.setLocationRelativeTo(null);
		
		/**Definir que dados são visualizados e por quem - atributos da classe**/
		this.user = user; 
		this.requester = requester;
		this.dados = dados;
		
		/**Retirar opções/visibilidades consoante seja administrador ou leitor**/
		if (requester==user) this.removeBttn.setVisible(false);
		
		/**Pôr dados nos respectivos campos**/
		if (user instanceof Leitor) {
			this.categoriaLabel.setText("Tipo");
			this.categoria.setVisible(false);
			if (((Leitor)user).getTipo()) this.isProf.setSelected(true);
			else this.isAluno.setSelected(true);
		}
		else {
			this.reqsBttn.setVisible(false);
			this.categoria.setText(((Admin)user).getCategoria());
			this.isProf.setVisible(false);
			this.isAluno.setVisible(false);
		}
		this.nome.setText(user.getNome());
		this.morada.setText(user.getMorada());
		this.telefone.setText(user.getTelefone());
		this.email.setText(user.getEmail());
		this.id.setText(""+user.getnInterno());
		this.dia.setText(""+user.getDataNascimento().getDia());
		this.mes.setText(""+user.getDataNascimento().getMes());
		this.ano.setText(""+user.getDataNascimento().getAno());
		
		/**Desactivar botão de OK (função - confirmar alterações**/
		this.okBttn.setVisible(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nome = new javax.swing.JTextField();
        morada = new javax.swing.JTextField();
        telefone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        categoria = new javax.swing.JTextField();
        dia = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        ano = new javax.swing.JTextField();
        nomeLabel = new javax.swing.JLabel();
        moradaLabel = new javax.swing.JLabel();
        telefoneLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        categoriaLabel = new javax.swing.JLabel();
        dataLabel = new javax.swing.JLabel();
        slash1 = new javax.swing.JLabel();
        slash2 = new javax.swing.JLabel();
        removeBttn = new javax.swing.JButton();
        editBttn = new javax.swing.JButton();
        reqsBttn = new javax.swing.JButton();
        okBttn = new javax.swing.JButton();
        isAluno = new javax.swing.JRadioButton();
        isProf = new javax.swing.JRadioButton();
        nomeLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        nome.setEditable(false);

        morada.setEditable(false);

        telefone.setEditable(false);
        telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                telefoneKeyReleased(evt);
            }
        });

        email.setEditable(false);

        id.setEditable(false);

        categoria.setEditable(false);

        dia.setEditable(false);

        mes.setEditable(false);

        ano.setEditable(false);

        nomeLabel.setText("Nome:");

        moradaLabel.setText("Morada:");

        telefoneLabel.setText("Telefone:");

        emailLabel.setText("E-mail:");

        categoriaLabel.setText("Categoria:");

        dataLabel.setText("Data de Nascimento:");

        slash1.setText("/");

        slash2.setText("/");

        removeBttn.setText("Remover");
        removeBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBttnActionPerformed(evt);
            }
        });

        editBttn.setText("Editar");
        editBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBttnActionPerformed(evt);
            }
        });

        reqsBttn.setText("Ver requisições");
        reqsBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqsBttnActionPerformed(evt);
            }
        });

        okBttn.setText("OK");
        okBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBttnActionPerformed(evt);
            }
        });

        buttonGroup1.add(isAluno);
        isAluno.setText("Aluno");
        isAluno.setEnabled(false);

        buttonGroup1.add(isProf);
        isProf.setText("Professor");
        isProf.setEnabled(false);

        nomeLabel1.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reqsBttn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeBttn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editBttn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(okBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeLabel)
                            .addComponent(moradaLabel)
                            .addComponent(telefoneLabel)
                            .addComponent(emailLabel)
                            .addComponent(categoriaLabel)
                            .addComponent(dataLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(morada)
                            .addComponent(nome)
                            .addComponent(telefone)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(isAluno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(isProf))
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(slash2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(slash1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeLabel1))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(morada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moradaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriaLabel)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isAluno)
                    .addComponent(isProf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataLabel)
                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slash1)
                    .addComponent(slash2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBttn)
                    .addComponent(removeBttn)
                    .addComponent(editBttn)
                    .addComponent(reqsBttn))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefoneKeyReleased
        if (this.telefone.getText().length()!=0) {
			try {
				this.telefone.setBackground(Color.white);
				Integer.parseInt(this.telefone.getText());
			}
			catch (NumberFormatException e) {
				this.telefone.setBackground(Color.red);
			}
		}
		else this.telefone.setBackground(Color.white);
    }//GEN-LAST:event_telefoneKeyReleased

    private void removeBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBttnActionPerformed
		int answer = JOptionPane.showConfirmDialog(null, "Tem a certeza que pretende remover este utlizador?", "", JOptionPane.YES_NO_OPTION);
		if (answer==1) return;
		if (((Admin)this.requester).removeUser(dados,this.user)==1)
			JOptionPane.showMessageDialog(null, "Utilizador removido com sucesso!", "Sucesso",JOptionPane.INFORMATION_MESSAGE);
        else 
            JOptionPane.showMessageDialog(null, "Utilizador não removido!", "Erro",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_removeBttnActionPerformed

    private void editBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBttnActionPerformed
        /**Tornar campos editáveis**/
        if (user instanceof Admin){
            this.categoria.setEditable(true);
            this.isAluno.setEnabled(true);
            this.isProf.setEnabled(true);
        }
        this.morada.setEditable(true);
        this.email.setEditable(true);
        this.telefone.setEditable(true);
        this.editBttn.setVisible(false);
        this.okBttn.setVisible(true);
    }//GEN-LAST:event_editBttnActionPerformed

    private void okBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBttnActionPerformed
        /**Ler novos valores**/
        this.user.setMorada(this.morada.getText());
        try {
            this.user.setTelefone(this.telefone.getText());
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Há campos mal preenchidos.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        this.user.setEmail(this.email.getText());
        if (user instanceof Admin) {
            ((Admin)this.user).setCategoria(this.categoria.getText());
        }
        else {
            ((Leitor)this.user).setTipo(this.isProf.isSelected());
        }
		
        /**Voltar a pôr os campos como não editáveis**/
        this.categoria.setEditable(false);
        this.isAluno.setEnabled(false);
        this.isProf.setEnabled(false);
        this.morada.setEditable(false);
        this.email.setEditable(false);
        this.telefone.setBackground(null);
        this.telefone.setEditable(false);
        this.editBttn.setVisible(true);
        this.okBttn.setVisible(false);
    }//GEN-LAST:event_okBttnActionPerformed

    private void reqsBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqsBttnActionPerformed
        if (((Leitor)this.user).getnReqs()==0) {
			JOptionPane.showMessageDialog(null, "O leitor não tem requisições neste momento.", "",JOptionPane.INFORMATION_MESSAGE);
			return;
		}
        Requisicao[] temp = Arrays.copyOfRange(((Leitor)user).getRequisicoes(), 0, ((Leitor)this.user).getnReqs());
        PickFromList j = new PickFromList(temp, requester, dados);
        j.setVisible(true);
	Search.frames.add(j);
    }//GEN-LAST:event_reqsBttnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ano;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField categoria;
    private javax.swing.JLabel categoriaLabel;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JTextField dia;
    private javax.swing.JButton editBttn;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField id;
    private javax.swing.JRadioButton isAluno;
    private javax.swing.JRadioButton isProf;
    private javax.swing.JTextField mes;
    private javax.swing.JTextField morada;
    private javax.swing.JLabel moradaLabel;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JLabel nomeLabel1;
    private javax.swing.JButton okBttn;
    private javax.swing.JButton removeBttn;
    private javax.swing.JButton reqsBttn;
    private javax.swing.JLabel slash1;
    private javax.swing.JLabel slash2;
    private javax.swing.JTextField telefone;
    private javax.swing.JLabel telefoneLabel;
    // End of variables declaration//GEN-END:variables
}
