/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphicInterface;

import globalclasses.Message;

import java.util.ArrayList;

import javax.swing.JFrame;
import interfaces.UIWindow;
import javax.swing.JOptionPane;

/**
 *
 * @author Rosa
 */
public class AgendaItem extends UIWindow {
    private static final long serialVersionUID = 1L;

    private final UIClient client;
    private final String meetingId;
    private ArrayList<Object> par;
    private int id;
    private int closed;
    /**
     * 
     * Creates new form AgendaItem
     * @param client
     * @param meetingId
     * @param item
     * @param closed
     */
    public AgendaItem(UIClient client, String meetingId, String item, int closed) {
        initComponents();
        
        client.lastWindow().setVisible(true);
        this.setLocationRelativeTo(client.lastWindow());
        client.lastWindow().setVisible(false);
        this.setTitle(client.getUsername());
        
        this.client = client;
        this.meetingId = meetingId;
        this.client.addWindow(this);
        this.closed = closed;
        
        loadData(item);
        updateClosed();
    }

    @Override
    public void setClosed(int closed) {
        this.closed = closed;
        updateClosed();
    }
    
    private void updateClosed() {
        if (description.getText().equals("DELETED")) {
            this.OKBtn.setVisible(false);
            this.deleteBtn.setVisible(false);
            this.description.setEditable(false);
            this.chatBtn.setVisible(false);
            this.addKeyBtn.setVisible(false);
            this.seeDecisionsBtn.setVisible(false);
            return;
        }
        if (closed==1) {
            this.addKeyBtn.setVisible(true);
            this.description.setEditable(false);
            this.deleteBtn.setVisible(false);
            this.OKBtn.setVisible(false);
            this.seeDecisionsBtn.setVisible(true);
            this.chatBtn.setVisible(true);
            return;
        }
        if (closed ==0) {
            this.addKeyBtn.setVisible(false);
            this.description.setEditable(true);
            this.deleteBtn.setVisible(true);
            this.OKBtn.setVisible(true);
            this.seeDecisionsBtn.setVisible(false);
            this.chatBtn.setVisible(false);
            return;
        }
        if (closed == 2) {
            this.chatBtn.setText("See Discussion");
            this.addKeyBtn.setVisible(false);
            this.description.setEditable(false);
            this.deleteBtn.setVisible(false);
            this.OKBtn.setVisible(false);
            this.seeDecisionsBtn.setVisible(true);
            this.chatBtn.setVisible(true);
            return;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OKBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CancelBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        addKeyBtn = new javax.swing.JButton();
        chatBtn = new javax.swing.JButton();
        seeDecisionsBtn = new javax.swing.JButton();
        numberLbl = new javax.swing.JTextField();
        historyBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        OKBtn.setText("Modify");
        OKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKBtnActionPerformed(evt);
            }
        });

        description.setColumns(20);
        description.setLineWrap(true);
        description.setRows(5);
        description.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descriptionKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(description);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Agenda Item");

        jLabel2.setText("Title");

        CancelBtn.setText("Back");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Description");

        title.setEditable(false);

        deleteBtn.setText("Delete Item");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        addKeyBtn.setText("Add Key Decision");
        addKeyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addKeyBtnActionPerformed(evt);
            }
        });

        chatBtn.setText("Join Discussion");
        chatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatBtnActionPerformed(evt);
            }
        });

        seeDecisionsBtn.setText("See Key Decisions");
        seeDecisionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeDecisionsBtnActionPerformed(evt);
            }
        });

        numberLbl.setEditable(false);

        historyBtn.setText("History");
        historyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(chatBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seeDecisionsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addKeyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(numberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(title)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(61, 61, 61)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(OKBtn)
                            .addComponent(deleteBtn)
                            .addComponent(historyBtn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelBtn)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OKBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn)
                        .addGap(18, 18, 18)
                        .addComponent(historyBtn)
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(chatBtn)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addKeyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(seeDecisionsBtn)
                                    .addComponent(CancelBtn))
                                .addGap(12, 12, 12))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKBtnActionPerformed
        par = new ArrayList<Object>();
        par.add(meetingId);
        par.add(this.description.getText());
        par.add(id);
        par.add(0);
        Message result = client.sendTCP(23, par);
        if (result.getResult()<0)
            JOptionPane.showMessageDialog(null, result.toString(), "Error",JOptionPane.ERROR_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, result.toString(), "Success",JOptionPane.INFORMATION_MESSAGE);
        leave();
    }//GEN-LAST:event_OKBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        par = new ArrayList<Object>();
        par.add(meetingId);
        par.add(this.description.getText());
        par.add(this.id);
        par.add(-1);
        Message result = client.sendTCP(23, par);
        if (result.getResult()<0)
            JOptionPane.showMessageDialog(null, result.toString(), "Error",JOptionPane.ERROR_MESSAGE);
        else 
            JOptionPane.showMessageDialog(null, result.toString(), "Success",JOptionPane.INFORMATION_MESSAGE);
        leave();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        leave();
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void addKeyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addKeyBtnActionPerformed
        String newKey = JOptionPane.showInputDialog("What did you decide?");
        if (newKey.equals("")) return;
        par = new ArrayList<Object>();
        par.add(this.id);
        par.add(newKey);
        par.add(meetingId);
        Message result = client.sendTCP(28,par);
        if (result.getResult()<0) {
            JOptionPane.showMessageDialog(null, result.toString(), "Error",JOptionPane.ERROR_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, result.toString(), "Success",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_addKeyBtnActionPerformed

    private void chatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatBtnActionPerformed
        par = new ArrayList<Object>();
        par.add(meetingId);
        par.add(id);
        Message result = client.sendTCP(31,par);
        if (result.getResult()==1) {
            new Chat(client,meetingId,id,result.toString(), closed);
            this.setVisible(false);
        }
        else
            JOptionPane.showMessageDialog(null, "There was an error performing this operation", "Error",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_chatBtnActionPerformed

    private void descriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descriptionKeyPressed
        if (this.description.getText().length()>Global.DESCRIPTIONLEN) {
            this.description.setText(this.description.getText().substring(0,Global.DESCRIPTIONLEN));
        }
        
    }//GEN-LAST:event_descriptionKeyPressed

    private void seeDecisionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeDecisionsBtnActionPerformed
        par = new ArrayList<Object>();
        par.add(1);
        par.add(meetingId);
        Message result = client.sendTCP(25, par);
        if (result.getResult()<0) {
            JOptionPane.showMessageDialog(null, result.getMsg().toString(), "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        String[] resultshere = result.toString().split("\n");
        /*So os deste agenda item*/
        String[] res = new String[resultshere.length];
        int j = 0;
        for (String resultshere1 : resultshere) {
            if (resultshere1.contains(this.title.getText())) {
                res[j++] = resultshere1;
            }
        }
        System.arraycopy(res, 0, resultshere, 0, j);
        
        new PickFromList(5, resultshere, client, "",closed);
        this.setVisible(false);
    }//GEN-LAST:event_seeDecisionsBtnActionPerformed

    private void historyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyBtnActionPerformed
        par = new ArrayList();
        par.add(meetingId);
        par.add(id);
        Message result = client.sendTCP(8, par);
        if (result.getResult()<0) {
            JOptionPane.showMessageDialog(null, result.getMsg().toString(), "Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        String[] resultshere = result.toString().split("\n");
        
        new PickFromList(8, resultshere, client, meetingId,closed);
        this.setVisible(false);
    }//GEN-LAST:event_historyBtnActionPerformed

    private void leave() {
        UIWindow previous = client.removeWindow();
        previous.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }
    
    private void loadData(String item) {
        String[] data = item.split("\t");
        if (data.length>1) {
            this.numberLbl.setText(data[0].trim());
            this.id = Integer.parseInt(data[0].trim());
            this.description.setText(data[2].trim());
            this.title.setText(data[1].trim());
            this.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(null, "Agenda Item was not loaded correctly", "Error",JOptionPane.ERROR_MESSAGE);
            leave();
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton OKBtn;
    private javax.swing.JButton addKeyBtn;
    private javax.swing.JButton chatBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextArea description;
    private javax.swing.JButton historyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numberLbl;
    private javax.swing.JButton seeDecisionsBtn;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
